apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dude-ingress
  namespace: team1
spec:
  hosts:
  - "dude.adamg.dev.okro.io"
  gateways:
  - dude-gateway
  http:
  - route:
    - destination:
        host: dude.team1.svc.cluster.local
        subset: v1
        port:
          number: 8080
      weight: 90
    - destination:
        host: dude.team1.svc.cluster.local
        subset: v2
        port:
          number: 8080
      weight: 10