apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: reflector
  namespace: team2
spec:
  rules:
  - services:
    - "reflector.team2.svc.cluster.local"
    paths:
    - "*"
    methods:
    - "GET"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: reflector-binding
  namespace: team2
spec:
  subjects:
  - user: "cluster.local/ns/team1/sa/reflector"
  roleRef:
    kind: ServiceRole
    name: reflector