version: '3'
services:
  dude:
    image: dude:${HELLOD_VERSION}
    command: [
      "--port=8080",
      "--metrics-port=8081",
      "--helloer-addr=helloer:5050",
      "--echoer-addr=echoer:6060",
      "--jaeger-addr=http://jaeger:14268"
    ]
    ports:
      - "8080:8080"
      - "8081:8081"

  helloer:
    image: helloer:${HELLOD_VERSION}
    command: [
      "--port=5050",
      "--metrics-port=5051",
      "--jaeger-addr=http://jaeger:14268"
    ]
    ports:
      - "5050:5050"
      - "5051:5051"

  echoer:
    image: echoer:${HELLOD_VERSION}
    command: [
      "--port=6060",
      "--metrics-port=6061",
      "--kafka-brokers=kafka:9092",
      "--error-topic=hellod.failures",
      "--jaeger-addr=http://jaeger:14268"
    ]
    ports:
      - "6060:6060"
      - "6061:6061"

  watcher:
    image: watcher:${HELLOD_VERSION}
    command: [
      "--metrics-port=7071",
      "--kafka-brokers=kafka:9092",
      "--error-topic=hellod.failures",
      "--jaeger-addr=http://jaeger:14268"
    ]
    ports:
      - "7071:7071"

  reflector:
    image: reflector:${HELLOD_VERSION}
    command: [
      "--port=4040",
      "--metrics-port=4041",
      "--dude-addr=dude:8080",
      "--reflector-addr=reflector:4040",
      "--jaeger-addr=http://jaeger:14268"
    ]
    ports:
      - "4040:4040"
      - "4041:4041"

  zk:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "hellod.failures:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411