apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watcher-v1
  namespace: team1
  labels:
    app: watcher
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: watcher
        version: v1
    spec:
      serviceAccountName: watcher
      containers:
      - name: watcher
        image: 520887410018.dkr.ecr.eu-west-1.amazonaws.com/okro/hellod/watcher:v1.0.0
        resources:
          requests:
            cpu: "10m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/okro
        ports:
        - containerPort: 7071
      volumes:
      - name: config-volume
        configMap:
          name: watcher-v1-cfg

