{
 "title": "Dude service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "service", "query": "dude" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "gRPC Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_io_client_completed_rpcs{job=\"$job\"}[1m])) by (grpc_client_method)",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(grpc_io_client_completed_rpcs{grpc_client_status!=\"OK\", job=\"$job\"}[1m])) by (grpc_client_method)) / (sum(rate(grpc_io_client_completed_rpcs{job=\"$job\"}[1m])) by (grpc_client_method)) * 100",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(grpc_io_client_roundtrip_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_client_method))",
       "legendFormat": "Median - {{grpc_client_method}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_io_client_roundtrip_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_client_method))",
       "legendFormat": "95th - {{grpc_client_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(opencensus_io_http_server_request_count{job=\"$job\"}[1m]))"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(opencensus_io_http_server_response_count_by_status_code{http_status!=\"200\", job=\"$job\"}[1m])) / sum(rate(opencensus_io_http_server_request_count{job=\"$job\"}[1m])) * 100",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(opencensus_io_http_server_latency_bucket{job=\"$job\"}[1m])) by (le))",
       "legendFormat": "Median"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket{job=\"$job\"}[1m])) by (le))",
       "legendFormat": "95th"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Echoer service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "service", "query": "echoer" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "gRPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{job=\"$job\"}[1m])) by (grpc_client_method)",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_io_server_completed_rpcs{grpc_server_status!=\"OK\", job=\"$job\"}[1m])) by (grpc_server_method)) / (sum(rate(grpc_io_server_completed_rpcs{job=\"$job\"}[1m])) by (grpc_server_method)) * 100",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_server_method))",
     "legendFormat": "Median - {{grpc_server_method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_server_method))",
     "legendFormat": "95th - {{grpc_server_method}}"
    }
   ]
  }
 ]
}
{
 "title": "Helloer service",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "service", "query": "helloer" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "gRPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs{job=\"$job\"}[1m])) by (grpc_client_method)",
     "legendFormat": "{{grpc_client_method}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(grpc_io_server_completed_rpcs{grpc_server_status!=\"OK\", job=\"$job\"}[1m])) by (grpc_server_method)) / (sum(rate(grpc_io_server_completed_rpcs{job=\"$job\"}[1m])) by (grpc_server_method)) * 100",
     "legendFormat": "{{grpc_server_method}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_server_method))",
     "legendFormat": "Median - {{grpc_server_method}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{job=\"$job\"}[1m])) by (le, grpc_server_method))",
     "legendFormat": "95th - {{grpc_server_method}}"
    }
   ]
  }
 ]
}