apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: team1
  name: team1
  namespace: team1-system
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - prometheus
        topologyKey: kubernetes.io/hostname
  alerting:
    alertmanagers:
    - name: alertmanager-team1
      namespace: team1-system
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 500Mi
  ruleSelector:
    matchLabels:
      prometheus: team1
      role: alert-rules
  serviceAccountName: prometheus-team1
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  storage:
    volumeClaimTemplate:
      metadata:
        annotations:
          annotation1: prometheus
      spec:
        resources:
          requests:
            storage: 80Gi
        storageClassName: gp2
  version: v2.3.1
