apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: team1
  name: prometheus-team1
  namespace: team1-system
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: team1
