apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoer-v1
  namespace: team1
  labels:
    app: echoer
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoer
        version: v1
    spec:
      serviceAccountName: echoer
      containers:
      - name: echoer
        image: 520887410018.dkr.ecr.eu-west-1.amazonaws.com/okro/hellod/echoer:v1.0.0
        resources:
          requests:
            cpu: "10m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/okro
        ports:
        - containerPort: 6060
        - containerPort: 6061
      volumes:
      - name: config-volume
        configMap:
          name: echoer-v1-cfg