apiVersion: v1
kind: Service
metadata:
  name: reflector
  namespace: team1
  labels:
    app: reflector
spec:
  ports:
  - port: 4040
    name: http
  - port: 4041
    name: metrics
  selector:
    app: reflector
