apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: dude-deps
  namespace: team1
spec:
  rules:
  - services:
    - "helloer.team1.svc.cluster.local"
    paths:
    - "/hello.v1.Hello/Hi"
    - "/hello.v1.Hello/Bye"
    methods: ["*"] # istio bug, should be optional
  - services:
    - "echoer.team1.svc.cluster.local"
    paths:
    - "/hello.v1.Echo/Echo"
    methods: ["*"] # istio bug, should be optional
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: dude-deps-binding
  namespace: team1
spec:
  subjects:
  - user: "cluster.local/ns/team1/sa/dude"
  roleRef:
    kind: ServiceRole
    name: dude-deps