apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: okro:team1:admins-edit-binding
  namespace: team1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:team1-admins
