apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: okro:team2:users-view-binding
  namespace: team2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:team2-users
