apiVersion: v1
kind: ConfigMap
metadata:
  name: dude-v1-cfg
  namespace: team1
  labels:
    app: dude
    version: v1
data:
  config.yaml: |-
    port: 8080
    metrics-port: 8081
    helloer-addr: helloer:5050
    echoer-addr: echoer:6060
    jaeger-addr: http://jaeger-collector.team1-system:14268
