apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloer-v1
  namespace: team1
  labels:
    app: helloer
    version: v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloer
        version: v1
    spec:
      serviceAccountName: helloer
      containers:
      - name: helloer
        image: 520887410018.dkr.ecr.eu-west-1.amazonaws.com/okro/hellod/helloer:v1.0.0
        resources:
          requests:
            cpu: "10m"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/okro
        ports:
        - containerPort: 5050
        - containerPort: 5051
      volumes:
      - name: config-volume
        configMap:
          name: helloer-v1-cfg
