apiVersion: v1
kind: Service
metadata:
  name: helloer
  namespace: team1
  labels:
    app: helloer
spec:
  ports:
  - port: 5050
    name: grpc
  - port: 5051
    name: metrics
  selector:
    app: helloer
