apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: bastions
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: $KOPS_BASTION_TYPE
  maxPrice: "$KOPS_BASTION_MAX_PRICE"
  maxSize: 3
  minSize: 3
  role: Bastion
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c
