apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: node-prometheus-eu-west1-a
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: $KOPS_NODE_TYPE
  maxPrice: "$KOPS_NODE_MAX_PRICE"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    okro.io/isolate: prometheus
  role: Node
  taints:
  - "okro.io/isolate=prometheus:NoSchedule"
  subnets:
  - eu-west-1a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: $NAME
  name: node-prometheus-eu-west1-b
spec:
  image: kope.io/k8s-1.9-debian-jessie-amd64-hvm-ebs-2018-03-11
  machineType: $KOPS_NODE_TYPE
  maxPrice: "$KOPS_NODE_MAX_PRICE"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    okro.io/isolate: prometheus
  role: Node
  taints:
  - "okro.io/isolate=prometheus:NoSchedule"
  subnets:
  - eu-west-1b