{
 "title": "Kubernetes Kafka resource metrics",
 "description": "Monitors Kafka metrics from Prometheus. Shows active controllers, partitions, ISR shrink rate, purgatory size etc. Uses JMX exporter.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{instance=~\"$Broker$\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\"$Broker$\"}"
    }
   ]
  },
  {
   "title": "ISR shrink rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinks_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "ISR expansion rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrexpands_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Delayed Fetch operation purgatory size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{instance=~\"$Broker$\"}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$Topics Bytes In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "$Topics Bytes out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "Unclean leader election per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kafka_controller_controllerstats_uncleanleaderelectionspersec{instance=~\"$Broker$\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Fetch requests in Purgatory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_fetch{instance=~\"$Broker.*$\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Consumer Fetch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Local request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems{request=\"FetchConsumer\",instance=~\"$Broker$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Remote request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems{request=\"FetchConsumer\",instance=~\"$Broker$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request queue consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems{request=\"FetchConsumer\",instance=~\"$Broker$\"}[1m]))"
    }
   ]
  }
 ]
}
{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum by(topic)(rate(kafka_server_BrokerTopicMetrics_Count{job=\"kafka\", name=\"MessagesInPerSec\", topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underreplicated) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total[1m])) by(instance)",
     "legendFormat": "In {{instance}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesout_total[1m])) by(instance)",
     "legendFormat": "Out {{instance}}"
    }
   ]
  }
 ]
}