kind: Service
apiVersion: v1
metadata:
  name: kafka
  labels:
    app: kafka
  namespace: okro-system
spec:
  clusterIP: None
  ports:
  - name: jmx-exporter
    protocol: TCP
    port: 80
    targetPort: 9000
  - name: node-exporter
    protocol: TCP
    port: 8080
    targetPort: 9001