apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kafka
  name: kafka
  namespace: okro-system
spec:
  endpoints:
  - interval: 30s
    port: jmx-exporter
    scheme: http
  - interval: 30s
    port: node-exporter
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: kafka
