apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kube-dns
  name: kube-dns
  namespace: okro-system
spec:
  endpoints:
  - interval: 15s
    port: http-metrics-skydns
  - interval: 15s
    port: http-metrics-dnsmasq
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
