apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka
  namespace: team1
spec:
  hosts:
  - kafka.external
  addresses:
  - 172.31.0.0/16
  ports:
  - name: tls-kafka
    number: 9494
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kafka-mtls
  namespace: team1
spec:
  host: kafka.external
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem