apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dude-gateway
  namespace: team1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "dude.adamg.dev.okro.io"
#    tls:
#      mode: SIMPLE
#      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
#      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dude-ingress
  namespace: team1
spec:
  hosts:
  - "dude.adamg.dev.okro.io"
  gateways:
  - dude-gateway
  http:
  - route:
    - destination:
        host: "dude.team1.svc.cluster.local"
        port:
          number: 8080